source 'https://rubygems.org'
ruby '3.1.3'

gem 'rails', '~> 7.0.0'
gem 'pg', '~> 1.4'
gem 'puma', '~> 5.0'
gem 'rack-cors'
gem 'bootsnap', require: false
gem 'dotenv-rails', groups: [:development, :production]

# GraphQL
gem 'graphql', '~> 2.0'
gem 'graphql-batch', '~> 0.5'

group :development, :test do
  gem 'debug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'pry-rails'
  gem 'graphiql-rails'
end

group :development do
  gem 'listen', '~> 3.3'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
